kind: Service
apiVersion: v1
metadata:
  name:  simple-site-service
spec:
  type: NodePort
  selector:
    app: simple-site
  ports:
  - protocol: TCP
    port: 80
    nodePort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-site-deployment
  labels:
    app: simple-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-site
  template:
    metadata:
      labels:
        app: simple-site
    spec:
      containers:
      - name: simple-site
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 80
